### ISSUE TITLE
WGCNAshiny 使用报错

### ISSUE THREAD

**Issue by sijiali-0107** [ShawnWx2019/WGCNA-shinyApp#3]
老师您好，非常感谢您为WGCNA分析提供的便利。
最近在使用WGCNAshiny时，发现无论旧版本还是新版本，都可以打开shinyapp界面，但都出现了报错，使用demo文件测试也是相同的报错。去年使用旧版本是没问题的，可以运行。
R4.2.2和4.3.1版本都尝试过，是相同的报错，数据上传时显示上传成功：
![4031ab1eef0a67ee6d2e9e13fc9fa93](https://github.com/ShawnWx2019/WGCNA-shinyApp/assets/132361149/4df0d433-a001-45ba-b294-16c217e9981a)
但后面选参数清洗时出现报错：Error:在为'as.data.frame'函数选择方法时评估x'参数出了错: argument is not a matrix
![13665c10a888e9a18f3d6e97d02900c](https://github.com/ShawnWx2019/WGCNA-shinyApp/assets/132361149/618de120-0f1d-4334-9694-15458e729280)
感谢老师和各位大佬提出解决建议。

**Comment by ShawnWx2019** [comment]
应该是app版本和依赖版本不匹配，请根据以下代码更新留下依赖包：
```r
devtools::install_github("ShawnWx2019/WGCNAShinyFun",ref = "master")
```

**Comment by sijiali-0107** [comment]
老师，我按这句代码更新之后还是相同的报错，app界面可以打开上传后进行下一步操作时报错：Error:在为'as.data.frame'函数选择方法时评估x'参数出了错: argument is not a matrix，同学电脑上没更新过，用的老版本，现在也是有这个报错

**Comment by ShawnWx2019** [comment]
> 老师，我按这句代码更新之后还是相同的报错，app界面可以打开上传后进行下一步操作时报错：Error:在为'as.data.frame'函数选择方法时评估x'参数出了错: argument is not a matrix，同学电脑上没更新过，用的老版本，现在也是有这个报错

可以的话把报错时整个网页界面截图我看下，我需要看下其他参数的选择，同时方便的话把你的数据发我邮箱:shawndrive2019@126.com

**Comment by sijiali-0107** [comment]
谢谢老师耐心帮助，问题已解决。出现报错原因：数据上传之后，在数据清洗阶段左边参数选完后还未点Update information就去点了Preview of Input选项卡，此时在Preview of Input选项卡下方出现了上述报错。
![image](https://github.com/ShawnWx2019/WGCNA-shinyApp/assets/132361149/e3caa16b-99b6-440b-944a-f9d35af0cbfb)

在点了Update information之后报错消失，可以继续运行。
