### ISSUE TITLE
 module.edge files contain same genes

### ISSUE THREAD

**Issue by Anees-caas** [ShawnWx2019/WGCNA-shinyApp#6]
Hi, I have performed the WGCNA using DEGs. When I am exporting the module.edge files for each module and drawing hub gene networks on cytoscape I am getting same genes in different modules.

**Comment by ShawnWx2019** [comment]
<img width="1211" alt="image" src="https://github.com/user-attachments/assets/fd8b4cba-1084-4950-b37f-26da44866aa9">
After switching modules each time, make sure to click "Start Analysis" in the order shown above to update the data for the corresponding module, and then click the "Choose the Threshold" button to generate a new table.

**Comment by Anees-caas** [comment]
Thanks sir @ShawnWx2019 solved.
